#!/bin/bash
source "scripts/tests/base_test.sh"
SCRIPT="scripts/02_flow_control/04_menu_loopp.sh"

test_case "Primera opción" \
  "echo -e \"1\n\4" | $SCRIPT" \
  "*" \
  0

test_case "Segunda opción" \
  "echo -e \"2\n\4\" | $SCRIPT" \
  "*" \
  0

test_case "Tercera opción" \
  "echo -e \"3\n\4" | $SCRIPT" \
  "*" \
  0

test_case "Cuarta opción" \
  "echo -e \"4\" | $SCRIPT" \
  "*" \
  1

test_case "Opción no válida" \
  "echo -e \"7\n\4" | $SCRIPT" \
  "Opción no válida" \
  0

summary || exit 1
